services:

  # 'Dock-dploy' container
  dock-dploy:
  
    container_name: dock-dploy
    
    image: hhftechnology/dock-dploy:latest    
    
    environment:
      - NODE_ENV=production
      
    ports:
      - "127.0.0.1:3099:3000"
      
    networks:
      - caddynet
    
    restart: unless-stopped


networks:
  caddynet:
    external: true

    
